apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-v7nf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-v7nf
    app.kubernetes.io/part-of: ci10t-786-0012-app
  name: devfile-sample-v7nf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-v7nf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-v7nf
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0012-tenant/ci10t-786-0012-app/devfile-sample-v7nf@sha256:42547ee9d3bd4e3cf6aa01268421305ce3e1cffea6528ea7fa331bede7ea888e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
